/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.29.2-32-g8ce6fb251 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.29.2-32-g8ce6fb251"
#endif
#define SDL_REVISION_NUMBER 0
